"""Initial migration

Revision ID: e28fb27ef5eb
Revises: 
Create Date: 2026-02-16 23:14:24.417764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e28fb27ef5eb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TYPE IF EXISTS objecttype CASCADE")
    
    # Satellite
    op.create_table('satellite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('norad_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('int_designator', sa.String(), nullable=True),
    sa.Column('object_type', sa.Enum('PAYLOAD', 'ROCKET_BODY', 'DEBRIS', 'UNKNOWN', name='objecttype'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_satellite_id'), 'satellite', ['id'], unique=False)
    op.create_index(op.f('ix_satellite_norad_id'), 'satellite', ['norad_id'], unique=True)
    op.create_index(op.f('ix_satellite_name'), 'satellite', ['name'], unique=False)
    op.create_index(op.f('ix_satellite_int_designator'), 'satellite', ['int_designator'], unique=False)

    # TLE
    op.create_table('tle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('satellite_id', sa.Integer(), nullable=False),
    sa.Column('epoch', sa.DateTime(), nullable=False),
    sa.Column('line1', sa.String(), nullable=False),
    sa.Column('line2', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['satellite_id'], ['satellite.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('satellite_id', 'epoch', name='_satellite_epoch_uc')
    )
    op.create_index(op.f('ix_tle_epoch'), 'tle', ['epoch'], unique=False)
    op.create_index(op.f('ix_tle_id'), 'tle', ['id'], unique=False)

    # ConjunctionEvent
    op.create_table('conjunctionevent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sat1_norad', sa.Integer(), nullable=False),
    sa.Column('sat1_name', sa.String(), nullable=False),
    sa.Column('sat2_norad', sa.Integer(), nullable=False),
    sa.Column('sat2_name', sa.String(), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(), nullable=False),
    sa.Column('event_time', sa.DateTime(), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=True),
    sa.Column('sat1_lat', sa.Float(), nullable=True),
    sa.Column('sat1_lon', sa.Float(), nullable=True),
    sa.Column('sat1_alt', sa.Float(), nullable=True),
    sa.Column('sat2_lat', sa.Float(), nullable=True),
    sa.Column('sat2_lon', sa.Float(), nullable=True),
    sa.Column('sat2_alt', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conjunctionevent_event_time'), 'conjunctionevent', ['event_time'], unique=False)
    op.create_index(op.f('ix_conjunctionevent_id'), 'conjunctionevent', ['id'], unique=False)
    op.create_index(op.f('ix_conjunctionevent_sat1_norad'), 'conjunctionevent', ['sat1_norad'], unique=False)
    op.create_index(op.f('ix_conjunctionevent_sat2_norad'), 'conjunctionevent', ['sat2_norad'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conjunctionevent_sat2_norad'), table_name='conjunctionevent')
    op.drop_index(op.f('ix_conjunctionevent_sat1_norad'), table_name='conjunctionevent')
    op.drop_index(op.f('ix_conjunctionevent_id'), table_name='conjunctionevent')
    op.drop_index(op.f('ix_conjunctionevent_event_time'), table_name='conjunctionevent')
    op.drop_table('conjunctionevent')
    
    op.drop_index(op.f('ix_tle_id'), table_name='tle')
    op.drop_index(op.f('ix_tle_epoch'), table_name='tle')
    op.drop_table('tle')
    
    op.drop_index(op.f('ix_satellite_int_designator'), table_name='satellite')
    op.drop_index(op.f('ix_satellite_name'), table_name='satellite')
    op.drop_index(op.f('ix_satellite_norad_id'), table_name='satellite')
    op.drop_index(op.f('ix_satellite_id'), table_name='satellite')
    op.drop_table('satellite')
    
    op.execute("DROP TYPE IF EXISTS objecttype CASCADE")
    # ### end Alembic commands ###
